$(function(){"use strict";if($('[data-wm-plugin="split-sections"]').length){if($('main.Index').length){$('body').addClass('sqs-seven-oh');console.log('seven oh');$('head').prepend('<link href="https://assets.codepen.io/3198845/WMSplitSections9720-70v3-0.css" rel="stylesheet">');}else if($('.sqs-seven-one').length){$('head').prepend('<link href="https://assets.codepen.io/3198845/WMSplitSections9720-71v3-1.css" rel="stylesheet">');}
$('[data-wm-plugin="split-sections"]').each(function(i){let index=i+1,splitSection,splitCount=2,splitWidths=[],$parentSectionId,stickySectionNum,sectionBackgroundColor,stickySection;if($(this).attr('data-split-count')){splitCount=parseInt($(this).attr('data-split-count'));}
if($('.sqs-seven-one').length){$parentSectionId=$(this).closest('section.page-section');}else if($('.sqs-seven-oh').length){$parentSectionId=$(this).closest('section.Index-page');}
$parentSectionId.addClass('wm-split-section wm-split-1').attr('data-wm-split-group',index);let j;for(j=1;j<splitCount;j++){let count=j+1;let nextSection=$('[data-wm-split-group="'+index+'"]').last().next();$(nextSection).addClass('wm-split-section wm-split-'+count).attr('data-wm-split-group',index);}
$(this).closest('.sqs-block-code').addClass('remove-height');$('[data-wm-split-group='+index+']').wrapAll('<div class="wm-split-sections" id="split-group-'+index+'"></div>');splitSection='#split-group-'+index;if($(this).attr('data-split-widths')){let widthData=$(this).attr('data-split-widths');splitWidths=widthData.split(',');}else{let evenWidth=(100/splitCount)+'%';for(let e=0;e<splitCount;e++){splitWidths.push(evenWidth);}}
let w;for(w=0;w<splitWidths.length;w++){$('#split-group-'+index).find('.wm-split-section').eq(w).css({'width':splitWidths[w]})}
if($(this).attr('data-sticky-section')){stickySectionNum=parseInt($(this).attr('data-sticky-section'));stickySectionNum=stickySectionNum-1;stickySection=$('#split-group-'+index).find('.wm-split-section').eq(stickySectionNum);$(stickySection).addClass('split-sticky');sectionBackgroundColor=$(stickySection).find('.section-background').css('background');$(splitSection).css({'background':sectionBackgroundColor})
if($('body').hasClass('tweak-fixed-header-style-scroll-back')){function checkScrollBack(){if($('#header .header-announcement-bar-wrapper').css('transform')==="matrix(1, 0, 0, 1, 0, 0)"){$('body').removeClass('scroll-back-up');$('body').addClass('scroll-back-down');}else{$('body').removeClass('scroll-back-down');$('body').addClass('scroll-back-up');}}
checkScrollBack();window.addEventListener('scroll',checkScrollBack);}}});let wmHeaderHeight;function adjustHeaderHeight(){if(wmHeaderHeight!=$('header#header').height()+"px"){setTimeout(function(){wmHeaderHeight=$('header#header').height()+"px";$(':root').css('--wm-header-height',wmHeaderHeight);},150);}}
if(window.self!==window.top){$('[data-test="frameToolbarEdit"]',parent.document).on('click',function(){$('.wm-split-section').unwrap();})}
adjustHeaderHeight();window.addEventListener("resize",adjustHeaderHeight);window.addEventListener('scroll',adjustHeaderHeight);window.dispatchEvent(new Event('resize'));}});